# Generated by Django 5.2.4 on 2025-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("capacity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Reserved", "Reserved"),
                            ("Occupied", "Occupied"),
                        ],
                        default="Free",
                        max_length=10,
                    ),
                ),
                ("time_left", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
