# Generated by Django 5.2.4 on 2025-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservationDate",
            field=models.DateField(),
        ),
    ]
